import { describe, it, expect, vi } from "vitest";
import {
  renderMarkdownToHtml,
  stripMarkdown,
  buildHtmlDocument,
  extractAssistantText,
  loadCss,
  ansiToHtml,
  wrapCodeBlocks,
} from "./render";

describe("renderMarkdownToHtml", () => {
  it("renders heading and paragraph", () => {
    const md = "# Hello\n\nWorld";
    const html = renderMarkdownToHtml(md);
    expect(html).toContain("<h1>Hello</h1>");
    expect(html).toContain("<p>World</p>");
  });

  it("renders code block with highlighting", () => {
    const md = "```ts\nconst x = 1;\n```";
    const html = renderMarkdownToHtml(md);
    expect(html).toContain("<pre>");
    expect(html).toContain("<code");
    expect(html).toContain("const");
  });

  it("renders code block with unknown language as plaintext", () => {
    const md = "```nonexistent_lang\nsome code\n```";
    const html = renderMarkdownToHtml(md);
    expect(html).toContain("<pre>");
    expect(html).toContain("<code");
    expect(html).toContain("some code");
  });

  it("renders table", () => {
    const md = "| A | B |\n|---|---|\n| 1 | 2 |";
    const html = renderMarkdownToHtml(md);
    expect(html).toContain("<table>");
    expect(html).toContain("<td>1</td>");
  });
});

describe("loadCss", () => {
  it("returns empty github CSS but catppuccin highlight when files are missing", () => {
    const result = loadCss("/nonexistent/path");
    expect(result.github).toBe("");
    expect(result.highlight).toContain("Catppuccin Mocha");
    expect(result.highlight).toContain(
      ".markdown-body .hljs-keyword { color: #cba6f7; }",
    );
  });
});

describe("stripMarkdown", () => {
  it("removes heading markers", () => {
    expect(stripMarkdown("# Hello")).toBe("Hello");
  });

  it("removes bold markers", () => {
    expect(stripMarkdown("**bold**")).toBe("bold");
  });

  it("removes code backticks", () => {
    expect(stripMarkdown("`code`")).toBe("code");
  });

  it("removes code fences", () => {
    const md = "```ts\nconst x = 1;\n```";
    expect(stripMarkdown(md)).toBe("const x = 1;");
  });

  it("removes link syntax keeping text", () => {
    expect(stripMarkdown("[text](url)")).toBe("text");
  });

  it("handles multiline", () => {
    const md = "# Title\n\nSome **bold** text.\n\n```\ncode\n```";
    expect(stripMarkdown(md)).toBe("Title\n\nSome bold text.\n\ncode");
  });
});

describe("buildHtmlDocument", () => {
  it("wraps body in full HTML document", () => {
    const doc = buildHtmlDocument("<p>hello</p>");
    expect(doc).toContain("<!DOCTYPE html>");
    expect(doc).toContain("<html");
    expect(doc).toContain("<p>hello</p>");
    expect(doc).toContain(".markdown-body");
  });

  it("includes thinking block when provided", () => {
    const doc = buildHtmlDocument("<p>hello</p>", "think content");
    expect(doc).toContain("<details");
    expect(doc).toContain("think content");
    expect(doc).toContain("</details>");
  });

  it("omits thinking block when not provided", () => {
    const doc = buildHtmlDocument("<p>hello</p>");
    expect(doc).not.toContain("<details");
  });

  it("renders ANSI colors in thinking block as HTML spans", () => {
    const thinking =
      "\x1b[38;2;203;166;247mThinking:\x1b[39m \x1b[38;2;166;173;200m部署完成\x1b[0m";
    const doc = buildHtmlDocument("<p>hello</p>", thinking);
    expect(doc).toContain(
      '<span style="color:rgb(203,166,247)">Thinking:</span>',
    );
    expect(doc).toContain(
      '<span style="color:rgb(166,173,200)">部署完成</span>',
    );
  });

  it("uses catppuccin-mocha syntax highlighting", () => {
    const doc = buildHtmlDocument("<p>hello</p>");
    expect(doc).toContain("background: #1e1e2e");
    expect(doc).toContain("color: #cdd6f4");
    // catppuccin-mocha highlight.js colors with .markdown-body prefix for specificity
    expect(doc).toContain(".markdown-body .hljs-keyword { color: #cba6f7; }");
    expect(doc).toContain(".markdown-body .hljs-string { color: #a6e3a1; }");
    expect(doc).toContain(".markdown-body .hljs-comment { color: #9399b2; }");
    expect(doc).toContain(".markdown-body .hljs-number { color: #fab387; }");
  });

  it("includes custom ctp-layout CSS rules", () => {
    const doc = buildHtmlDocument("<p>hello</p>");
    // body background
    expect(doc).toContain("background: #1e1e2e");
    // max-width 820px
    expect(doc).toContain("max-width: 820px");
    // paragraph styles
    expect(doc).toContain("font-size: 15px");
    expect(doc).toContain("line-height: 1.75");
    // header
    expect(doc).toContain("Pi Agent Reply");
    expect(doc).toContain('<header class="page-header"');
    // footer
    expect(doc).toContain("Generated by pi · Catppuccin Mocha");
    expect(doc).toContain('<footer class="page-footer"');
  });

  it("includes custom ctp-heading CSS rules", () => {
    const doc = buildHtmlDocument("<p>hello</p>");
    // H1 gradient
    expect(doc).toContain("-webkit-background-clip: text");
    expect(doc).toContain("linear-gradient(135deg, #f5c2e7, #cba6f7, #89b4fa)");
    // H1 left border
    expect(doc).toContain("border-left: 4px solid #cba6f7");
    // H2 blue + bottom border
    expect(doc).toContain(".markdown-body h2");
    expect(doc).toContain("color: #89b4fa");
    expect(doc).toContain("border-bottom: 2px solid #45475a");
    // H3 teal
    expect(doc).toContain(".markdown-body h3");
    expect(doc).toContain("color: #94e2d5");
    // H4 yellow
    expect(doc).toContain(".markdown-body h4");
    expect(doc).toContain("color: #f9e2af");
  });

  it("includes custom ctp-table CSS rules", () => {
    const doc = buildHtmlDocument("<p>hello</p>");
    // table outer
    expect(doc).toContain(".markdown-body table");
    expect(doc).toContain("border-collapse: separate");
    expect(doc).toContain("border-spacing: 0");
    // table header
    expect(doc).toContain(".markdown-body th");
    expect(doc).toContain("text-transform: uppercase");
    // zebra stripe
    expect(doc).toContain(".markdown-body tr:nth-child(even)");
    // row hover
    expect(doc).toContain(".markdown-body tr:hover");
  });

  it("includes custom ctp-list CSS rules", () => {
    const doc = buildHtmlDocument("<p>hello</p>");
    // unordered list marker
    expect(doc).toContain(".markdown-body ul");
    expect(doc).toContain("list-style: none");
    // ordered list marker color
    expect(doc).toContain(".markdown-body ol");
    expect(doc).toContain("color: #cba6f7");
  });

  it("includes custom ctp-blockquote CSS rules", () => {
    const doc = buildHtmlDocument("<p>hello</p>");
    expect(doc).toContain(".markdown-body blockquote");
    expect(doc).toContain("border-left: 4px solid #cba6f7");
    expect(doc).toContain("background: #232436");
    expect(doc).toContain("font-style: italic");
  });

  it("wraps code blocks in output", () => {
    const body =
      '<pre><code class="hljs language-ts">const x = 1;</code></pre>';
    const doc = buildHtmlDocument(body);
    expect(doc).toContain('<div class="code-block-wrapper">');
    expect(doc).toContain('<div class="code-block-header">');
    expect(doc).toContain("📋 复制");
  });

  it("includes copy button JavaScript", () => {
    const doc = buildHtmlDocument("<p>hello</p>");
    expect(doc).toContain("function copyCode(");
    expect(doc).toContain("navigator.clipboard.writeText");
    expect(doc).toContain("✅ 已复制");
  });

  it("includes code block CSS rules", () => {
    const doc = buildHtmlDocument("<p>hello</p>");
    expect(doc).toContain(".code-block-wrapper");
    expect(doc).toContain("border-radius: 8px");
    expect(doc).toContain(".code-block-header");
    expect(doc).toContain(".code-block-header button:hover");
  });

  it("includes custom ctp-inline CSS rules", () => {
    const doc = buildHtmlDocument("<p>hello</p>");
    // inline code
    expect(doc).toContain(".markdown-body code");
    expect(doc).toContain("border: 1px solid #45475a");
    expect(doc).toContain("background: #232436");
    // links
    expect(doc).toContain(".markdown-body a");
    expect(doc).toContain("border-bottom: 1px solid");
    expect(doc).toContain(".markdown-body a:hover");
    // horizontal rules
    expect(doc).toContain(".markdown-body hr");
    expect(doc).toContain("border-top: 1px solid #45475a");
    // images
    expect(doc).toContain(".markdown-body img");
    expect(doc).toContain("border-radius: 8px");
  });

  it("includes updated thinking block CSS", () => {
    const doc = buildHtmlDocument("<p>hello</p>", "some thinking");
    expect(doc).toContain("🧠 思考过程");
    expect(doc).toContain(".thinking-block");
    expect(doc).toContain("background: #232436");
    expect(doc).toContain("border: 1px solid #45475a");
    expect(doc).toContain("border-radius: 8px");
  });
});

describe("wrapCodeBlocks", () => {
  it("wraps code block with language header and copy button", () => {
    const input =
      '<pre><code class="hljs language-typescript">const x = 1;</code></pre>';
    const result = wrapCodeBlocks(input);
    expect(result).toContain('<div class="code-block-wrapper">');
    expect(result).toContain('<div class="code-block-header">');
    expect(result).toContain("<span>typescript</span>");
    expect(result).toContain("📋 复制");
    expect(result).toContain(
      '<pre><code class="hljs language-typescript">const x = 1;</code></pre>',
    );
  });

  it("does not wrap non-code content", () => {
    const input =
      '<p>hello</p><pre><code class="hljs language-ts">code</code></pre>';
    const result = wrapCodeBlocks(input);
    expect(result).toContain("<p>hello</p>");
    expect(result).toContain("code-block-wrapper");
  });

  it("handles multiple code blocks", () => {
    const input =
      '<pre><code class="hljs language-ts">a</code></pre><p>text</p><pre><code class="hljs language-py">b</code></pre>';
    const result = wrapCodeBlocks(input);
    const matches = result.match(/code-block-wrapper/g);
    expect(matches).toHaveLength(2);
  });

  it("handles code block with plaintext language", () => {
    const input =
      '<pre><code class="hljs language-plaintext">text</code></pre>';
    const result = wrapCodeBlocks(input);
    expect(result).toContain("<span>plaintext</span>");
  });
});

describe("ansiToHtml", () => {
  it("converts true-color ANSI to HTML spans", () => {
    const input = "\x1b[38;2;255;0;0mred\x1b[39m";
    expect(ansiToHtml(input)).toBe(
      '<span style="color:rgb(255,0,0)">red</span>',
    );
  });

  it("handles reset code (0)", () => {
    const input = "\x1b[38;2;255;0;0mred\x1b[0mnormal";
    expect(ansiToHtml(input)).toBe(
      '<span style="color:rgb(255,0,0)">red</span>normal',
    );
  });

  it("escapes HTML in non-ANSI text", () => {
    expect(ansiToHtml("<script>")).toBe("&lt;script&gt;");
  });

  it("ignores unsupported ANSI codes", () => {
    const input = "\x1b[1mbold\x1b[0m";
    expect(ansiToHtml(input)).toBe("\x1b[1mbold");
  });

  it("handles plain text without ANSI", () => {
    expect(ansiToHtml("hello world")).toBe("hello world");
  });

  it("closes remaining spans at end of string", () => {
    const input = "\x1b[38;2;100;100;100mgray";
    expect(ansiToHtml(input)).toBe(
      '<span style="color:rgb(100,100,100)">gray</span>',
    );
  });

  it("handles adjacent color spans", () => {
    const input =
      "\x1b[38;2;255;0;0mr\x1b[38;2;0;255;0mg\x1b[38;2;0;0;255mb\x1b[0m";
    expect(ansiToHtml(input)).toBe(
      '<span style="color:rgb(255,0,0)">r</span>' +
        '<span style="color:rgb(0,255,0)">g</span>' +
        '<span style="color:rgb(0,0,255)">b</span>',
    );
  });

  it("ignores incomplete true-color sequences (missing B)", () => {
    const input = "\x1b[38;2;255;0mtext";
    expect(ansiToHtml(input)).toBe("\x1b[38;2;255;0mtext");
  });

  it("ignores incomplete true-color sequences (missing all RGB)", () => {
    const input = "\x1b[38;2mtext";
    expect(ansiToHtml(input)).toBe("\x1b[38;2mtext");
  });

  it("handles bare bracket color sequences (pi thinking format)", () => {
    const input = "[38;2;203;166;247mThinking:[39m [38;2;166;173;200mdone[39m";
    expect(ansiToHtml(input)).toBe(
      '<span style="color:rgb(203,166,247)">Thinking:</span> <span style="color:rgb(166,173,200)">done</span>',
    );
  });

  it("handles text ending with reset code", () => {
    const input = "\x1b[38;2;255;0;0mred\x1b[0m";
    expect(ansiToHtml(input)).toBe(
      '<span style="color:rgb(255,0,0)">red</span>',
    );
  });

  it("handles color code at end with no trailing text", () => {
    const input = "\x1b[38;2;100;100;100m";
    expect(ansiToHtml(input)).toBe(
      '<span style="color:rgb(100,100,100)"></span>',
    );
  });

  it("ignores 256-color mode (38;5)", () => {
    const input = "\x1b[38;5;196mtext\x1b[0m";
    expect(ansiToHtml(input)).toBe("\x1b[38;5;196mtext");
  });
});

describe("extractAssistantText", () => {
  it("extracts text from TextContent array", () => {
    const content = [{ type: "text" as const, text: "hello" }];
    expect(extractAssistantText(content)).toBe("hello");
  });

  it("extracts text from mixed content (skips tool calls)", () => {
    const content = [
      { type: "text" as const, text: "hello" },
      { type: "toolCall" as const, id: "1", name: "bash", arguments: {} },
    ];
    expect(extractAssistantText(content)).toBe("hello");
  });

  it("extracts thinking from ThinkingContent", () => {
    const content = [{ type: "thinking" as const, thinking: "reasoning" }];
    expect(extractAssistantText(content, "thinking")).toBe("reasoning");
  });

  it("returns empty string for empty array", () => {
    expect(extractAssistantText([])).toBe("");
  });

  it("returns empty string when text is undefined", () => {
    const content = [{ type: "text" as const, text: undefined }];
    expect(extractAssistantText(content)).toBe("");
  });

  it("returns empty string when thinking is undefined", () => {
    const content = [{ type: "thinking" as const, thinking: undefined }];
    expect(extractAssistantText(content, "thinking")).toBe("");
  });
});
