import type { Config } from "./types";

export const config = {
  defaultPolicy: "allow",
  judgeModel: "openai-codex/gpt-5.6-luna",
  auditModel: "openai-codex/gpt-5.6-sol",
  auditThinking: "high",
  judgeTimeoutMs: 8000,
  childPolicy: "deny-on-unsafe",
  permission: {
    ask_user_question: "allow",
    bash: {
      "*": "ask",
      "awk *": "ask",
      "biome *": "allow",
      "bun add *": "allow",
      "bun build *": "allow",
      "bun install *": "allow",
      "bun remove *": "allow",
      "bun run *": "allow",
      "bun test *": "allow",
      "bun x *": "allow",
      env: "deny",
      "env |*": "deny",
      "env|*": "deny",
      "export -p": "deny",
      "export -p |*": "deny",
      "export -p|*": "deny",
      "gh --help": "allow",
      "gh --version": "allow",
      "gh * --help": "allow",
      "gh api --method GET *": "allow",
      "gh api -X GET *": "allow",
      "gh api --method GET *--field*": "ask",
      "gh api --method GET *--hostname*": "ask",
      "gh api --method GET *--input*": "ask",
      "gh api --method GET *--method*": "ask",
      "gh api --method GET *--raw-field*": "ask",
      "gh api --method GET *-F*": "ask",
      "gh api --method GET *-H*": "ask",
      "gh api --method GET *-X*": "ask",
      "gh api --method GET *-f*": "ask",
      "gh api -X GET *--field*": "ask",
      "gh api -X GET *--hostname*": "ask",
      "gh api -X GET *--input*": "ask",
      "gh api -X GET *--method*": "ask",
      "gh api -X GET *--raw-field*": "ask",
      "gh api -X GET *-F*": "ask",
      "gh api -X GET *-H*": "ask",
      "gh api -X GET *-X*": "ask",
      "gh api -X GET *-f*": "ask",
      "gh auth status": "allow",
      "gh auth status *": "allow",
      "gh issue list": "allow",
      "gh issue list *": "allow",
      "gh issue status": "allow",
      "gh issue status *": "allow",
      "gh issue view": "allow",
      "gh issue view *": "allow",
      "gh pr checks": "allow",
      "gh pr checks *": "allow",
      "gh pr comment *": "ask",
      "gh pr diff": "allow",
      "gh pr diff *": "allow",
      "gh pr list": "allow",
      "gh pr list *": "allow",
      "gh pr status": "allow",
      "gh pr status *": "allow",
      "gh pr view": "allow",
      "gh pr view *": "allow",
      "gh release list": "allow",
      "gh release list *": "allow",
      "gh release view": "allow",
      "gh release view *": "allow",
      "gh repo list": "allow",
      "gh repo list *": "allow",
      "gh repo view": "allow",
      "gh repo view *": "allow",
      "gh run list": "allow",
      "gh run list *": "allow",
      "gh run view": "allow",
      "gh run view *": "allow",
      "gh run watch": "allow",
      "gh run watch *": "allow",
      "gh workflow list": "allow",
      "gh workflow list *": "allow",
      "gh workflow view": "allow",
      "gh workflow view *": "allow",
      "git add *": "allow",
      "git blame *": "allow",
      "git branch -r": "allow",
      "git branch -r *": "allow",
      "git branch --contains *": "allow",
      "git branch --show-current": "allow",
      "git check-ignore *": "allow",
      "git config --get *": "allow",
      "git config --get-all *": "allow",
      "git config user.email": "allow",
      "git config user.name": "allow",
      "git diff": "allow",
      "git diff *": "allow",
      "git log *": "allow",
      "git ls-files": "allow",
      "git ls-files *": "allow",
      "git merge-base *": "allow",
      "git merge-base HEAD main": "allow",
      "git merge-base HEAD master": "allow",
      "git remote -v": "allow",
      "git remote get-url *": "allow",
      "git rev-parse *": "allow",
      "git show": "allow",
      "git show *": "allow",
      "git show *--ext-diff*": "ask",
      "git show *--textconv*": "ask",
      "git status": "allow",
      "git status *": "allow",
      "git symbolic-ref *": "allow",
      "git worktree list": "allow",
      "git worktree list *": "allow",
      "node *": "allow",
      "npm install *": "allow",
      "npm run *": "allow",
      "npm test *": "allow",
      "pi update": "allow",
      "pi update --extensions": "allow",
      "pnpm install *": "allow",
      "pnpm run *": "allow",
      "pnpm sst *": "deny",
      "pnpm test *": "allow",
      printenv: "deny",
      "printenv *": "deny",
      "rm -rf *": "deny",
      "rtk find *": "allow",
      "rtk git add *": "allow",
      "rtk git branch --contains *": "allow",
      "rtk git branch --show-current": "allow",
      "rtk git diff": "allow",
      "rtk git diff *": "allow",
      "rtk git log *": "allow",
      "rtk git merge-base *": "allow",
      "rtk git merge-base HEAD main": "allow",
      "rtk git merge-base HEAD master": "allow",
      "rtk git rev-parse *": "allow",
      "rtk git status": "allow",
      "rtk git status *": "allow",
      "sed *": "allow",
      set: "deny",
      "set |*": "deny",
      "set|*": "deny",
      "sst *": "deny",
      "sudo *": "ask",
      "tsc *": "allow",
      "vitest *": "allow",
    },
    ctx_execute: "allow",
    external_directory: {
      "*": "ask",
      "~/.pi/agent": "allow",
      "~/.cargo/registry/*": "allow",
      "~/.npm/_cacache/*": "allow",
      "~/Library/Caches/*": "allow",
    },
    path: {
      "*": "allow",
      "*.env": "deny",
      "*.env.*": "deny",
      "*.env.example": "allow",
      "*.key": "deny",
      "*.pem": "deny",
      "*.token": "deny",
      "*password*": "deny",
      "*secret*": "deny",
      ".netrc": "deny",
      "credentials.*": "deny",
      "id_ecdsa*": "deny",
      "id_ed25519*": "deny",
      "id_rsa*": "deny",
      "kubeconfig*": "deny",
      "~/.aws/*": "deny",
      "~/.kube/*": "deny",
      "~/.npmrc": "deny",
      "~/.ssh/*": "deny",
    },
    todo: "allow",
  },
} as const satisfies Config;
