import { buildHtmlDocument } from "../web-preview/index";
import type { JudgeLogEntry } from "./stats";

const PAGE_CSS = `body {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
  font-size: 14px;
  line-height: 1.6;
  color: #cdd6f4;
  background: #1e1e2e;
  margin: 0;
  padding: 0;
}
.page-header {
  padding: 1.5rem 1rem 1rem;
  text-align: center;
  border-bottom: 1px solid #313244;
}
.page-header h1 {
  font-size: 1.4rem;
  font-weight: 700;
  color: #cba6f7;
  margin: 0 0 0.35rem;
}
.page-header p {
  color: #7f849c;
  font-size: 0.85rem;
  margin: 0 0 0.9rem;
}
.filters {
  display: flex;
  justify-content: center;
  gap: 0.5rem;
}
.filter-btn {
  background: #313244;
  border: 1px solid #45475a;
  color: #a6adc8;
  padding: 4px 16px;
  border-radius: 999px;
  font-size: 0.8rem;
  cursor: pointer;
  transition: background 0.15s, color 0.15s;
}
.filter-btn:hover {
  background: #45475a;
}
.filter-btn.active {
  background: #cba6f7;
  border-color: #cba6f7;
  color: #1e1e2e;
  font-weight: 600;
}
main {
  max-width: 1080px;
  margin: 0 auto;
  padding: 1.5rem 1rem 2rem;
}
table {
  width: 100%;
  border-collapse: separate;
  border-spacing: 0;
  border: 1px solid #313244;
  border-radius: 8px;
  overflow: hidden;
}
th, td {
  padding: 10px 14px;
  text-align: left;
  vertical-align: top;
  border-bottom: 1px solid #313244;
}
th {
  background: #313244;
  color: #cba6f7;
  font-size: 0.8rem;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 0.5px;
  white-space: nowrap;
}
tbody tr:last-child td {
  border-bottom: none;
}
tbody tr:nth-child(even) td {
  background: #232436;
}
tbody tr:hover td {
  background: #313244;
}
td.num {
  color: #7f849c;
  white-space: nowrap;
}
td.command code {
  background: #11111b;
  border: 1px solid #45475a;
  border-radius: 4px;
  padding: 2px 6px;
  color: #94e2d5;
  font-size: 0.85em;
  word-break: break-all;
  white-space: pre-wrap;
}
td.safe {
  color: #a6e3a1;
  font-weight: 600;
  white-space: nowrap;
}
td.unsafe {
  color: #f38ba8;
  font-weight: 600;
  white-space: nowrap;
}
td.approved {
  color: #a6e3a1;
  font-weight: 600;
  white-space: nowrap;
}
td.denied {
  color: #f38ba8;
  font-weight: 600;
  white-space: nowrap;
}
td.na {
  color: #585b70;
  white-space: nowrap;
}
.page-footer {
  text-align: center;
  padding: 1rem 1rem 2rem;
  font-size: 0.8rem;
  color: #7f849c;
  border-top: 1px solid #313244;
}`;

const FILTER_JS = `function filterLogs(filter) {
  var buttons = document.querySelectorAll('.filter-btn');
  for (var i = 0; i < buttons.length; i++) {
    buttons[i].classList.toggle('active', buttons[i].dataset.filter === filter);
  }
  var rows = document.querySelectorAll('tbody tr');
  for (var j = 0; j < rows.length; j++) {
    var safe = rows[j].dataset.safe;
    var show = filter === 'all' ||
      (filter === 'safe' && safe === 'true') ||
      (filter === 'unsafe' && safe === 'false');
    rows[j].style.display = show ? '' : 'none';
  }
}`;

export function renderJudgeLogPage(logs: JudgeLogEntry[]): string {
  const rows = logs
    .map((log, index) => renderRow(log, index + 1))
    .reverse()
    .join("\n");

  return buildHtmlDocument({
    title: "法官判断日志",
    bodyHtml: `  <header class="page-header">
    <h1>法官判断日志</h1>
    <p>当前会话法官判断（共 ${logs.length} 条）</p>
    <div class="filters">
      <button class="filter-btn active" data-filter="all" onclick="filterLogs('all')">全部</button>
      <button class="filter-btn" data-filter="safe" onclick="filterLogs('safe')">安全</button>
      <button class="filter-btn" data-filter="unsafe" onclick="filterLogs('unsafe')">不安全</button>
    </div>
  </header>
  <main>
    <table>
      <thead>
        <tr><th>#</th><th>工具</th><th>命令</th><th>判定</th><th>用户</th><th>用途</th><th>理由</th></tr>
      </thead>
      <tbody>
${rows}
      </tbody>
    </table>
  </main>
  <footer class="page-footer">Generated by pi · my-permission</footer>`,
    css: PAGE_CSS,
    js: FILTER_JS,
  });
}

function renderRow(log: JudgeLogEntry, num: number): string {
  const verdictClass = log.safe ? "safe" : "unsafe";
  const verdictLabel = log.safe ? "✓ 安全" : "✗ 不安全";
  const scoreText = log.score !== undefined ? `（${log.score}/10）` : "";
  const userCell =
    log.safe !== false
      ? '<td class="na">—</td>'
      : log.userApproved
        ? '<td class="approved">✓ 批准</td>'
        : '<td class="denied">✗ 拒绝</td>';
  return `        <tr data-safe="${log.safe}">
          <td class="num">${num}</td>
          <td>${escapeHtml(log.toolName)}</td>
          <td class="command"><code>${escapeHtml(log.value)}</code></td>
          <td class="${verdictClass}">${verdictLabel}${scoreText}</td>
          ${userCell}
          <td>${escapeHtml(log.toolFor)}</td>
          <td>${escapeHtml(log.reason)}</td>
        </tr>`;
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}
